name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: npm install and build webpack
        run: |
          npm ci
          npm run build --if-present

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016]
        node-version: [8.x, 10.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install and test
        run: |
          npm ci
          npm test
        env:
          CI: true
